### PR TITLE
Support dynamic library build

### PR DESCRIPTION
**Pull request by Cyberhan123**

### CODE REVIEW

**Comment by Cyberhan123** [comment]
@leejet  This PR to reslove https://github.com/leejet/stable-diffusion.cpp/issues/63

**Comment by JohnClaw** [comment]
Hope that somebody will compile and upload SD.cpp.dll

**Comment by Cyberhan123** [comment]
Don’t merge the code yet, I need to complete the testing of go.
https://github.com/seasonjs/stable-diffusion

**Comment by leejet** [comment]
Thank you for your contribution. Before merging this PR, I believe there are a few things that still need to be done:

1. There is no need to modify `stable-diffusion.cpp/stable-diffusion.h`, so please keep `stable-diffusion.cpp/stable-diffusion.h` as they are.

2. There is no need to expose `sd_txt2img_options` as a C-level API. In fact, I think the exposed API should remain simple and only the following interfaces should be exposed:

```cpp
STABLE_DIFFUSION_API void *create_stable_diffusion(int n_threads,
                                                   bool vae_decode_only,
                                                   bool free_params_immediately,
                                                   RNGType rng_type);

STABLE_DIFFUSION_API void destroy_stable_diffusion(void* sd);

STABLE_DIFFUSION_API bool load_from_file(void* sd, const char* file_path, Schedule d);

STABLE_DIFFUSION_API uint8_t* txt2img(void* sd,
                                      const char* prompt,
                                      const char* negative_prompt,
                                      float cfg_scale,
                                      int width,
                                      int height,
                                      SampleMethod sample_method,
                                      int sample_steps,
                                      int64_t seed);

STABLE_DIFFUSION_API uint8_t* txt2img(void* sd,
                                      const uint8_t* init_img,
                                      size_t init_img_size,
                                      const char* prompt,
                                      const char* negative_prompt,
                                      float cfg_scale,
                                      int width,
                                      int height,
                                      SampleMethod sample_method,
                                      int sample_steps,
                                      float strength,
                                      int64_t seed);

STABLE_DIFFUSION_API void set_stable_diffusion_log_level(const char* level);

STABLE_DIFFUSION_API const char* get_stable_diffusion_system_info();
```

3. Please use `add_subdirectory` to include `ggml`, otherwise, it will lose automatic detection of SIMD and support for CUBLAS/CLBLAS. There is no need to bring these over from `ggml`'s `CMakeLists.txt`, and this will introduce additional work when I synchronize changes from upstream `ggml`.

**Comment by Cyberhan123** [comment]
1. I will clean up the relevant code and logic at the end and restore `stable-diffusion.cpp/stable-diffusion.h` and
`stable-diffusion.cpp/stable-diffusion.h`
2. I have commented these implementations in the code. In order to enable lossless conversion of golang or other programming languages, writing in this way is also a helpless move.

```golang
//https://github.com/seasonjs/stable-diffusion/blob/main/binding.go#L231
// Use setter to handle purego max args limit less than 9
// see https://github.com/ebitengine/purego/pull/7
// https://github.com/ebitengine/purego/blob/4db9e9e813d0f24f3ccc85a843d2316d2d2a70c6/func.go#L104
func (c *CSDCtx) StableDiffusionTextToImage(prompt string, negativePrompt string, cfgScale float32, width int, height int, sampleMethod SampleMethod, sampleSteps int, seed int64) []byte {
	var outputSize int64
	options := c.csd.cNewSdImg2imgOptions()
	c.csd.cSetTxt2imgPrompt(options, prompt)
	c.csd.cSetTxt2imgNegativePrompt(options, negativePrompt)
	c.csd.cSetTxt2imgCfgScale(options, cfgScale)
	c.csd.cSetTxt2imgSize(options, width, height)
	c.csd.cSetTxt2imgSampleMethod(options, string(sampleMethod))
	c.csd.cSetTxt2imgSampleSteps(options, sampleSteps)
	c.csd.cSetTxt2imgSeed(options, seed)
	output := c.csd.cTxt2img(c.ctx, options, &outputSize)
	runtime.KeepAlive(output)
	data := unsafe.Slice(output, outputSize)
	return data
}

```
3. Use `add_subdirectory`
In this case, the dynamic library cannot be compiled correctly because `ggml` is not compiled in.
So I referred to the method of `llama.cpp`
My ability here is limited and I need your help. How can I export correctly even when using `add_subdirectory`?

https://github.com/ggerganov/llama.cpp/blob/master/CMakeLists.txt#L639C1-L649C14
```CMake
add_library(ggml OBJECT
            ggml.c
            ggml.h
            ggml-alloc.c
            ggml-alloc.h
            ${GGML_SOURCES_CUDA} ${GGML_HEADERS_CUDA}
            ${GGML_SOURCES_OPENCL} ${GGML_HEADERS_OPENCL}
            ${GGML_SOURCES_METAL} ${GGML_HEADERS_METAL}
            ${GGML_SOURCES_MPI} ${GGML_HEADERS_MPI}
            ${GGML_SOURCES_EXTRA} ${GGML_HEADERS_EXTRA}
            )
```

**Comment by Cyberhan123** [comment]
I can't bear to disturb you. I want to ask you about the third question: the setting of add_subdirectory.
@ggerganov

**Comment by Cyberhan123** [comment]
@leejet 
I have now completed the debugging of txt2img on Windows but the effect is not satisfactory. Is there something wrong with the process of converting it into pictures? If you can answer it, I would really appreciate it.

```golang
//https://github.com/seasonjs/stable-diffusion/blob/main/binding_test.go
func writeToFile(byteData []byte, height int, width int) {

	img := image.NewRGBA(image.Rect(0, 0, width, height))
        //Is this the right way for me to perform rgba conversion?
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			idx := (y * x) * 3
			img.Set(x, y, color.RGBA{
				R: byteData[idx],
				G: byteData[idx+1],
				B: byteData[idx+2],
				A: 255,
			})
		}
	}

	file, err := os.Create("./data/output.png")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	err = png.Encode(file, img)
	if err != nil {
		panic(err)
	}

	println("Image saved as output.png")
}

func TestSD(t *testing.T) {
	sd, err := NewCStableDiffusion(getLibrary())
	if err != nil {
		t.Log(err)
	}
	info := sd.cGetStableDiffusionSystemInfo()
	t.Log(info)
	ctx := sd.NewStableDiffusionCtx(20, true, true, STD_DEFAULT_RNG)
	defer ctx.Close()
	ctx.StableDiffusionLoadFromFile("./data/sd_v1-4_ggml_Q5.bin", DEFAULT)
	data := ctx.StableDiffusionTextToImage("a lovely cat", "", 7.0, 512, 512, EULER_A, 20, 42)
	writeToFile(data, 128, 128)
}
```
Is this the right way for me to perform rgba conversion?
```golang
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			idx := (y * x) * 3
			img.Set(x, y, color.RGBA{
				R: byteData[idx],
				G: byteData[idx+1],
				B: byteData[idx+2],
				A: 255,
			})
		}
	}
```
output

**Comment by AngryLoki** [comment]
> Is there something wrong with the process of converting it into pictures? 

@Cyberhan123, try to check with 320x320. I experienced similar issues with small images - maybe this is related to #24 and solutions from there could also help.

**Comment by Cyberhan123** [comment]
> > Is there something wrong with the process of converting it into pictures?
> 
> @Cyberhan123, try to check with 320x320. I experienced similar issues with small images - maybe this is related to #24 and solutions from there could also help.

Thanks for your help. it works for me

**Comment by Cyberhan123** [comment]
When I was using `add_subdirectory` to manage ggml, I found that there would be mistake:
```
=== RUN   TestNewStableDiffusionAutoModelPredict
    sd_test.go:12: {-1 true true CUDA_RNG DEFAULT out of frame, lowers, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, username, watermark, signature 7 520 520 EULER_A 20 0.4 42 PNG}
[INFO]  stable-diffusion.cpp:2834 - loading model from './models/sd_v1-4_ggml_Q5.bin'
[INFO]  stable-diffusion.cpp:2862 - model type: SD1.x
[INFO]  stable-diffusion.cpp:2870 - ftype: q5_0
[INFO]  stable-diffusion.cpp:3100 - total params size = 1478.08MB (clip 81.13MB, unet 1302.44MB, vae 94.51MB)
[INFO]  stable-diffusion.cpp:3102 - loading model from './models/sd_v1-4_ggml_Q5.bin' completed, taking 1.99s
[INFO]  stable-diffusion.cpp:3128 - running in eps-prediction mode
    sd_test.go:25: open ./data/output2.png: The system cannot find the path specified.
[INFO]  stable-diffusion.cpp:3379 - condition graph use 94.50MB of memory: params 81.13MB, runtime 13.37MB (static 10.44MB, dynamic 2.93MB)
[INFO]  stable-diffusion.cpp:3379 - condition graph use 94.50MB of memory: params 81.13MB, runtime 13.37MB (static 10.44MB, dynamic 2.93MB)
[INFO]  stable-diffusion.cpp:4242 - get_learned_condition completed, taking 0.31s
[INFO]  stable-diffusion.cpp:4258 - start sampling
GGML_ASSERT: stable-diffusion.cpp\ggml\src\ggml.c:5733: a->ne[0] == b->ne[0] && a->ne[1] == b->ne[1] && a->ne[3] == b->ne[3]
```
I don't quite understand what the problem is. I need friends who are proficient in C/C++ to help me.

**Comment by Cyberhan123** [comment]
I converted this to a draft and readjusted it

**Comment by Cyberhan123** [comment]
> Thank you for your contribution. Before merging this PR, I believe there are a few things that still need to be done:
> 
> 1. There is no need to modify `stable-diffusion.cpp/stable-diffusion.h`, so please keep `stable-diffusion.cpp/stable-diffusion.h` as they are.
> 2. There is no need to expose `sd_txt2img_options` as a C-level API. In fact, I think the exposed API should remain simple and only the following interfaces should be exposed:
> 
> ```c++
> STABLE_DIFFUSION_API void *create_stable_diffusion(int n_threads,
>                                                    bool vae_decode_only,
>                                                    bool free_params_immediately,
>                                                    RNGType rng_type);
> 
> STABLE_DIFFUSION_API void destroy_stable_diffusion(void* sd);
> 
> STABLE_DIFFUSION_API bool load_from_file(void* sd, const char* file_path, Schedule d);
> 
> STABLE_DIFFUSION_API uint8_t* txt2img(void* sd,
>                                       const char* prompt,
>                                       const char* negative_prompt,
>                                       float cfg_scale,
>                                       int width,
>                                       int height,
>                                       SampleMethod sample_method,
>                                       int sample_steps,
>                                       int64_t seed);
> 
> STABLE_DIFFUSION_API uint8_t* txt2img(void* sd,
>                                       const uint8_t* init_img,
>                                       size_t init_img_size,
>                                       const char* prompt,
>                                       const char* negative_prompt,
>                                       float cfg_scale,
>                                       int width,
>                                       int height,
>                                       SampleMethod sample_method,
>                                       int sample_steps,
>                                       float strength,
>                                       int64_t seed);
> 
> STABLE_DIFFUSION_API void set_stable_diffusion_log_level(const char* level);
> 
> STABLE_DIFFUSION_API const char* get_stable_diffusion_system_info();
> ```
> 
> 3. Please use `add_subdirectory` to include `ggml`, otherwise, it will lose automatic detection of SIMD and support for CUBLAS/CLBLAS. There is no need to bring these over from `ggml`'s `CMakeLists.txt`, and this will introduce additional work when I synchronize changes from upstream `ggml`.

So far I have done，but without test. When I perfect it, I will convert the draft into a formal PR.
If anyone following this issue has any ideas, please let me know.

**Comment by Cyberhan123** [comment]
Currently, for this project, my needs exceed the scope of maintenance and increase the complexity of cmake. I will implement it in the https://github.com/seasonjs/stable-diffusion.cpp-build project.

**Comment by markyfsun** [comment]
> When I was using `add_subdirectory` to manage ggml, I found that there would be mistake:
> 
> ```
> === RUN   TestNewStableDiffusionAutoModelPredict
>     sd_test.go:12: {-1 true true CUDA_RNG DEFAULT out of frame, lowers, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, username, watermark, signature 7 520 520 EULER_A 20 0.4 42 PNG}
> [INFO]  stable-diffusion.cpp:2834 - loading model from './models/sd_v1-4_ggml_Q5.bin'
> [INFO]  stable-diffusion.cpp:2862 - model type: SD1.x
> [INFO]  stable-diffusion.cpp:2870 - ftype: q5_0
> [INFO]  stable-diffusion.cpp:3100 - total params size = 1478.08MB (clip 81.13MB, unet 1302.44MB, vae 94.51MB)
> [INFO]  stable-diffusion.cpp:3102 - loading model from './models/sd_v1-4_ggml_Q5.bin' completed, taking 1.99s
> [INFO]  stable-diffusion.cpp:3128 - running in eps-prediction mode
>     sd_test.go:25: open ./data/output2.png: The system cannot find the path specified.
> [INFO]  stable-diffusion.cpp:3379 - condition graph use 94.50MB of memory: params 81.13MB, runtime 13.37MB (static 10.44MB, dynamic 2.93MB)
> [INFO]  stable-diffusion.cpp:3379 - condition graph use 94.50MB of memory: params 81.13MB, runtime 13.37MB (static 10.44MB, dynamic 2.93MB)
> [INFO]  stable-diffusion.cpp:4242 - get_learned_condition completed, taking 0.31s
> [INFO]  stable-diffusion.cpp:4258 - start sampling
> GGML_ASSERT: stable-diffusion.cpp\ggml\src\ggml.c:5733: a->ne[0] == b->ne[0] && a->ne[1] == b->ne[1] && a->ne[3] == b->ne[3]
> ```
> 
> I don't quite understand what the problem is. I need friends who are proficient in C/C++ to help me.

I also got this problem when image height or width cannot be divided by 32.

**Pull request closed without merging**
