### PR TITLE
feat: add convert api

### PR DESCRIPTION
**Pull request by leejet**

### CODE REVIEW

**Comment by Cyberhan123** [comment]
@leejet Due to the API refactor, I think I don't need to add additional package code. Are you willing to let github ci support building dynamic libraries? If you are willing, I am willing to modify ci and submit a PR. My plan is to add windows cuda , rocm, mac metal dynamic library support.

**Comment by Green-Sky** [comment]
@Cyberhan123 is there a point in not using avx2 for linux/mac amd64 ?

**Comment by Cyberhan123** [comment]
> @Cyberhan123 is there a point in not using avx2 for linux/mac amd64 ?

Only supports avx2

**Comment by Green-Sky** [comment]
@leejet would be cool if we could bake in a custom vae, like the f16 fix for xl.

**Comment by Jonathhhan** [comment]
> Only supports avx2

I use avx2 and CUDA with Linux.

**Comment by leejet** [comment]
> Are you willing to let github ci support building dynamic libraries?

@Cyberhan123 I'd appreciate someone helping to set up the corresponding CI. I haven't had much free time lately to work on this.

**Comment by leejet** [comment]
> @leejet would be cool if we could bake in a custom vae, like the f16 fix for xl.

I'm not quite following what you mean. It's been possible to specify custom vae for a while now.

**Comment by Green-Sky** [comment]
> > @leejet would be cool if we could bake in a custom vae, like the f16 fix for xl.
> 
> I'm not quite following what you mean. It's been possible to specify custom vae for a while now.

but to have them merged/replaced into the same gguf

**Comment by Cyberhan123** [comment]
>  I'd appreciate someone helping to set up the corresponding CI. I haven't had much free time lately to work on this.

Okay, after ggml is merged and the PR of rocm is completed, I will implement it.

**Pull request merged**
