### PR TITLE
[SYCL] Add SYCL Backend Support for Intel GPUs

### PR DESCRIPTION
**Pull request by zhentaoyu**
## What Does This PR Do
https://github.com/leejet/stable-diffusion.cpp/issues/308
Hi, it's a pr for initial `SYCL` backend support for Intel GPUs (Arch-770, etc.). We are happy to hear the feedback from stable-diffusion.cpp community. If you have any comments or questions, please feel free to leave them in this pr.
cc @airMeng, @luoyu-intel, @hshen14

## TODO or Issues
- [x] update `ggml` commit when `tsembd` sycl op is merged (https://github.com/ggerganov/llama.cpp/pull/8707). 
- [ ] can not generate imgs with large `-H` and `-W` (for example, 1024, seems [sycl issue](https://github.com/intel/llvm/issues/4255)): `Provided range is out of integer limits. Pass '-fno-sycl-id-queries-fit-in-int' to disable range check.` It's caused by the `im2col` sycl op [sum_of_products of `global_range` exceeds INT_MAX](https://github.com/ggerganov/ggml/blob/73c3287813f8977d778d3eb5006660b5ae04f288/src/ggml-sycl.cpp#L1759-L1760). We need to modify `im2col` kernel or implement another more efficient conv op in the future.
- [x] more tests

### build command
`cmake .. -DSD_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx`
doc link is [here](https://github.com/zhentaoyu/stable-diffusion.cpp/tree/enable_sycl?tab=readme-ov-file#using-sycl)

### test machine
|ID|        Device Type|                                   Name|Version|Max compute units  |Max work group   |Max sub group|Global  mem size   |       Driver version|
|--|-------------------|---------------------------------------|-------|-------|--------|-----|-------|---------------------|
| 0| [level_zero:gpu:0]|         Intel Data Center GPU Max 1100|    1.3|    448|    1024|   32| 51539M|            1.3.27191|

### text2img
- sd v1-4
   `./build/bin/sd -m ../sd_models/sd-v1-4.ckpt -p "a lovely cat" -o "output_sycl_sd1-4.png"`
   output: `[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 8.35s` 
    
image

- sd v1-5 
  `./build/bin/sd -m ../sd_models/v1-5-pruned-emaonly.safetensors -p "a lovely cat" -o "output_sycl_sd1-5.png"`
  output: `[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 8.44s`
   
image
- sd v2
  `./build/bin/sd -m ../sd_models/v2-1_768-nonema-pruned.safetensors -p "a lovely cat" -o "output_sycl_sd2.png"`
  output: `[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 6.04s`
image

- sd xl
 `./build/bin/sd -m ../sd_models/sdxl/sd_xl_base_1.0.safetensors --vae ../sd_models/sdxl/sdxl_vae.safetensors -H 512 -W 512 -p "a lovely cat" -o "output_sycl_sdxl.png" --seed 16`
 output: `[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 12.46s`
image

- sd v3
 `./build/bin/sd -m ../sd_models/sd3_medium_incl_clips_t5xxlfp16.safetensors  -H 512 -W 512 -p "a lovely cat holding a sign says \"Stable Diffusion CPP\"" --cfg-scale 4.5 --sampling-method euler -v -o "output_sycl_sd3.png"`
output: `[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 13.25s`
image

### quantization type
command: `./build/bin/sd -m ../sd_models/sd3_medium_incl_clips_t5xxlfp16.safetensors  -H 512 -W 512 -p "a lovely cat holding a sign says \"Stable Diffusion CPP\"" --cfg-scale 4.5 --sampling-method euler -v -o "output_sycl_sd3_q8_0.png" --type q8_0`

| f16 |   q8_0 | q5_0 | q5_1 | q4_0 | q4_1|
| --   | ------  | ----- | -----  | ----- | ----  |
|13.25s | 12.84s | 12.88s| 12.91s |    12.86s    |   12.99s       |
|    14829.53MB    |      8030.57MB    |     5310.99MB     |     5764.25MB     |  4404.46MB      |    4857.73MB       | 
| image |  image | image  | image   | image  | image |       

### img2img
command: ` ./build/bin/sd --mode img2img -m ../sd_models/sd3_medium_incl_clips_t5xxlfp16.safetensors -p "cat with blue eyes" -i ./assets/f32.png --strength 0.4 -o "output_sycl_img2img.png"`

output: 
```bash
[INFO ] stable-diffusion.cpp:1172 - generating image: 1/1 - seed 42
  |==================================================| 9/9 - 2.37it/s
[INFO ] stable-diffusion.cpp:1203 - sampling completed, taking 4.21s
[INFO ] stable-diffusion.cpp:1211 - generating 1 latent images completed, taking 4.58s
[INFO ] stable-diffusion.cpp:1214 - decoding 1 latents
[INFO ] stable-diffusion.cpp:1224 - latent 1 decoded, taking 0.75s
[INFO ] stable-diffusion.cpp:1228 - decode_first_stage completed, taking 0.75s
[INFO ] stable-diffusion.cpp:1424 - img2img completed in 1.87s
```
image

### LCM-Lora
command: `./build/bin/sd -m ../sd_models/v1-5-pruned-emaonly.safetensors -p "a lovely cat<lora:lcm-lora-sdv1-5:1>" --steps 4 --lora-model-dir ../sd_models/lora/ -v --cfg-scale 1 -o "output_sycl_lcm_lora.png"`
output: `[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 4.08s`
image

### PhotoMaker
command: `./build/bin/sd -m ../sd_models/sdxl/sdxlUnstableDiffusers_v11.safetensors  --vae ../sd_models/sdxl/sdxl_vae.safetensors --stacked-id-embd-dir ../sd_models/photo_maker/photomaker-v1.safetensors --input-id-images-dir ./assets/photomaker_examples/scarletthead_woman/ -p "a girl img, retro futurism, retro game art style but extremely beautiful, intricate details, masterpiece, best quality, space-themed, cosmic, celestial, stars, galaxies, nebulas, planets, science fiction, highly detailed" -n "realistic, photo-realistic, worst quality, greyscale, bad anatomy, bad hands, error, text" --cfg-scale 5.0  --sampling-method euler -H 640 -W 640 --style-ratio 15 -o "output_sycl_photomaker.png"`

output: `[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 17.38s`
image

### Upscale
command: `./build/bin/sd -m ../sd_models/sd3_medium_incl_clips_t5xxlfp16.safetensors  -H 640 -W 640 -p "a lovely cat holding a sign says \"Stable Diffusion CPP\"" --cfg-scale 4.5 --sampling-method euler --upscale-model ../sd_models/upscale/RealESRGAN_x4plus_anime_6B.pth -v -o "output_sycl_sd3_upscale.png" --seed 100`

output: 
```bash
[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 17.99s
[DEBUG] upscaler.cpp:28   - Using SYCL backend
[INFO ] upscaler.cpp:36   - Upscaler weight type: f16
[INFO ] esrgan.hpp:156  - loading esrgan from '../sd_models/upscale/RealESRGAN_x4plus_anime_6B.pth'
[DEBUG] ggml_extend.hpp:988  - esrgan params backend buffer size =   8.53 MB(VRAM) (192 tensors)
[INFO ] model.cpp:740  - load ../sd_models/upscale/RealESRGAN_x4plus_anime_6B.pth using checkpoint format
[DEBUG] model.cpp:1258 - init from '../sd_models/upscale/RealESRGAN_x4plus_anime_6B.pth'
[DEBUG] model.cpp:1389 - loading tensors from ../sd_models/upscale/RealESRGAN_x4plus_anime_6B.pth
[INFO ] esrgan.hpp:175  - esrgan model loaded
[INFO ] upscaler.cpp:50   - upscaling from (640 x 640) to (2560 x 2560)
[DEBUG] upscaler.cpp:64   - upscale work buffer size: 150.00 MB
[DEBUG] ggml_extend.hpp:496  - tile work buffer size: 3.19 MB
[DEBUG] ggml_extend.hpp:939  - esrgan compute buffer size: 416.00 MB(VRAM)
[INFO ] ggml_extend.hpp:510  - processing 49 tiles
  |==================================================| 49/49 - 6.99it/s
[INFO ] upscaler.cpp:79   - input_image_tensor upscaled, taking 7.37s
```
image

### TAESD
command: `./build/bin/sd -m ../sd_models/v1-5-pruned-emaonly.safetensors -p "a lovely cat" --taesd ../sd_models/taesd/diffusion_pytorch_model.safetensors -o "output_sycl_taesd.png"`
output: `[INFO ] stable-diffusion.cpp:1328 - txt2img completed in 7.80s`
image

### CODE REVIEW

**Comment by luoyu-intel** [comment]
Do we have any reference performance data? like, what is the latency of A100 for each model.

**Comment by zhentaoyu** [comment]
> Do we have any reference performance data? like, what is the latency of A100 for each model.

I only have A30 for now. Will update a table soon.

**Review by Nuullll — APPROVED** [review]
I happened to be working on this recently.
LGTM! The code change is basically identical with my local version :-P

FP16 performance is bad -- it's even worse than using fp32. We can address that later.

**Comment by zhentaoyu** [comment]
> > Do we have any reference performance data? like, what is the latency of A100 for each model.
> 
> I only have A30 for now. Will update a table soon.

Test commands are from the **text2img** section of PR description.
model | A30 | PVC | ratio
-- | -- | -- | --
sd1-4 | 4.47 | 8.35 | 0.535329
sd1-5 | 4.49 | 8.44 | 0.531991
sd2 | 3.84 | 6.04 | 0.635762
sd_xl | 6.04 | 12.46 | 0.484751
sd3 | 7.45 | 13.25 | 0.562264

`GPU Max 1100` can achieve about 50%~60% of `A30` latency.

**Comment by Green-Sky** [comment]
Can you please add units to the performance data? until states, it can be both it/s and s/it, as well as total sec ...

**Comment by zhentaoyu** [comment]
> Can you please add units to the performance data? until stated, it can be both it/s and s/it, as well as total sec ...

sorry, added.

**Comment by airMeng** [comment]
@leejet anything else needed to be merged?

**Comment by zhentaoyu** [comment]
This PR is ready for review now. There still has an issue that sycl backend can not generate images with large `H` and `W`. Will try to fix it in a later PR (the main efforts are from `ggml` side).

**Comment by zhentaoyu** [comment]
@leejet, cloud you please take a look at this PR if you have free time? Thanks a lot.

**Comment by leejet** [comment]
Excellent work! Thank you for your contribution.

**Comment by cheeseng** [comment]
I tried to use my intel gpu with this, able to build successfully but when try to run I got the following error: 

```
[SYCL] call ggml_check_sycl
ggml_check_sycl: GGML_SYCL_DEBUG: 0
ggml_check_sycl: GGML_SYCL_F16: yes
can not find preferred GPU platform
Exception caught at file:/home/cheeseng/stable-diffusion.cpp/ggml/src/ggml-sycl.cpp, line:1859, func:operator()
terminate called after throwing an instance of 'std::runtime_error'
  what():  can not find preferred GPU platform
Aborted (core dumped)
```

Is there anything I am missed?  Here's my gpu info: 

```
~$ lspci -k | grep -EA3 'VGA|3D|Display'
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
	DeviceName: Onboard - Video
	Subsystem: Tongfang Hongkong Limited CoffeeLake-H GT2 [UHD Graphics 630]
	Kernel driver in use: i915
--
01:00.0 VGA compatible controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
	Subsystem: Tongfang Hongkong Limited GP107M [GeForce GTX 1050 Mobile]
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
```

**Comment by zhentaoyu** [comment]
> I tried to use my intel gpu with this, able to build successfully but when try to run I got the following error:
> 
> ```
> [SYCL] call ggml_check_sycl
> ggml_check_sycl: GGML_SYCL_DEBUG: 0
> ggml_check_sycl: GGML_SYCL_F16: yes
> can not find preferred GPU platform
> Exception caught at file:/home/cheeseng/stable-diffusion.cpp/ggml/src/ggml-sycl.cpp, line:1859, func:operator()
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  can not find preferred GPU platform
> Aborted (core dumped)
> ```
> 
> Is there anything I am missed? Here's my gpu info:
> 
> ```
> ~$ lspci -k | grep -EA3 'VGA|3D|Display'
> 00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
> 	DeviceName: Onboard - Video
> 	Subsystem: Tongfang Hongkong Limited CoffeeLake-H GT2 [UHD Graphics 630]
> 	Kernel driver in use: i915
> --
> 01:00.0 VGA compatible controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
> 	Subsystem: Tongfang Hongkong Limited GP107M [GeForce GTX 1050 Mobile]
> 	Kernel driver in use: nvidia
> 	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
> ```

Hi, @cheeseng, does `sycl-ls` print anything?

**Comment by cheeseng** [comment]
> > I tried to use my intel gpu with this, able to build successfully but when try to run I got the following error:
> > ```
> > [SYCL] call ggml_check_sycl
> > ggml_check_sycl: GGML_SYCL_DEBUG: 0
> > ggml_check_sycl: GGML_SYCL_F16: yes
> > can not find preferred GPU platform
> > Exception caught at file:/home/cheeseng/stable-diffusion.cpp/ggml/src/ggml-sycl.cpp, line:1859, func:operator()
> > terminate called after throwing an instance of 'std::runtime_error'
> >   what():  can not find preferred GPU platform
> > Aborted (core dumped)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there anything I am missed? Here's my gpu info:
> > ```
> > ~$ lspci -k | grep -EA3 'VGA|3D|Display'
> > 00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
> > 	DeviceName: Onboard - Video
> > 	Subsystem: Tongfang Hongkong Limited CoffeeLake-H GT2 [UHD Graphics 630]
> > 	Kernel driver in use: i915
> > --
> > 01:00.0 VGA compatible controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
> > 	Subsystem: Tongfang Hongkong Limited GP107M [GeForce GTX 1050 Mobile]
> > 	Kernel driver in use: nvidia
> > 	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
> > ```
> 
> Hi, @cheeseng, does `sycl-ls` print anything?

@zhentaoyu Sorry I just noticed this, here's my `sycl-ls` output: 

```
~$ sycl-ls
[opencl:cpu][opencl:0] Intel(R) OpenCL, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz OpenCL 3.0 (Build 0) [2024.18.7.0.11_160000]
```

**Comment by zhentaoyu** [comment]
> > > I tried to use my intel gpu with this, able to build successfully but when try to run I got the following error:
> > > ```
> > > [SYCL] call ggml_check_sycl
> > > ggml_check_sycl: GGML_SYCL_DEBUG: 0
> > > ggml_check_sycl: GGML_SYCL_F16: yes
> > > can not find preferred GPU platform
> > > Exception caught at file:/home/cheeseng/stable-diffusion.cpp/ggml/src/ggml-sycl.cpp, line:1859, func:operator()
> > > terminate called after throwing an instance of 'std::runtime_error'
> > >   what():  can not find preferred GPU platform
> > > Aborted (core dumped)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is there anything I am missed? Here's my gpu info:
> > > ```
> > > ~$ lspci -k | grep -EA3 'VGA|3D|Display'
> > > 00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
> > > 	DeviceName: Onboard - Video
> > > 	Subsystem: Tongfang Hongkong Limited CoffeeLake-H GT2 [UHD Graphics 630]
> > > 	Kernel driver in use: i915
> > > --
> > > 01:00.0 VGA compatible controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
> > > 	Subsystem: Tongfang Hongkong Limited GP107M [GeForce GTX 1050 Mobile]
> > > 	Kernel driver in use: nvidia
> > > 	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
> > > ```
> > 
> > 
> > Hi, @cheeseng, does `sycl-ls` print anything?
> 
> @zhentaoyu Sorry I just noticed this, here's my `sycl-ls` output:
> 
> ```
> ~$ sycl-ls
> [opencl:cpu][opencl:0] Intel(R) OpenCL, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz OpenCL 3.0 (Build 0) [2024.18.7.0.11_160000]
> ```

Hi, @cheeseng, `sycl-ls` does not show any `level_zero:gpu` device. You can refer to [this doc](https://github.com/ggerganov/llama.cpp/blob/master/docs/backend/SYCL.md#hardware) for more information.

**Pull request merged**
