### PR TITLE
feat: Control Net support + Textual Inversion (embeddings)

### PR DESCRIPTION
**Pull request by FSSRepo**
I implemented a Control Net here; it's somewhat similar to the encoder phase of stable diffusion, but with some convolutional layers.

### Usage

```bash
./bin/sd --mode txt2img -p "a person" -m ../models/sd-v1-4.ckpt --control-net models/control_openpose-fp16.safetensors --control-image assets/control.png
```

### Some examples

| Conditioning | Result 1 | Result 2 |
|----------|----------|----------|
| none | output | output |
| control | output_controlnet | output_net2 |
| control_2 | output | output_net |
| control_3 | output | | 

**NOTE**: Requires more of 4 GB of VRAM, peak memory usage 3.6 GB (Out Of Memory in Windows). Use `--control-net-cpu` to keep Control Net with CPU backend

### CODE REVIEW

**Comment by ggerganov** [comment]
For me it fails in a different way:

```bash
make -j && ./bin/sd --mode txt2img -p "a person" -m ../models/sd-v1-4.ckpt
```

```
[INFO]  stable-diffusion.cpp:6105 - loading model from '../models/sd-v1-4.ckpt'
[INFO]  model.cpp:641  - load ../models/sd-v1-4.ckpt using checkpoint format
[INFO]  stable-diffusion.cpp:6131 - Stable Diffusion 1.x 
[INFO]  stable-diffusion.cpp:6137 - Stable Diffusion weight type: f32
[INFO]  stable-diffusion.cpp:6296 - total memory buffer size = 2731.37MB (clip 470.66MB, unet 2165.24MB, vae 95.47MB)
[INFO]  stable-diffusion.cpp:6298 - loading model from '../models/sd-v1-4.ckpt' completed, taking 9.89s
[INFO]  stable-diffusion.cpp:6312 - running in eps-prediction mode
[INFO]  stable-diffusion.cpp:5334 - loading control net from 'models/control_openpose-fp16.safetensors'
[INFO]  model.cpp:638  - load models/control_openpose-fp16.safetensors using safetensors format
ggml_tallocr_alloc: not enough space in the buffer (needed 1376030498560, largest block available 109550971676)
GGML_ASSERT: /Users/ggerganov/development/github/stable-diffusion.cpp/ggml/src/ggml-alloc.c:116: !"not enough space in the buffer"
Abort trap: 6
```

**Comment by FSSRepo** [comment]
Try specifying `--type f16`

**Comment by ggerganov** [comment]
Now it completes, but `output.png` is black

<details>

```
Option: 
    n_threads:         16
    mode:              txt2img
    model_path:        ../models/sd-v1-4.ckpt
    wtype:             f16
    vae_path:          
    taesd_path:        
    esrgan_path:       
    output_path:       output.png
    init_img:          
    prompt:            a person
    negative_prompt:   
    cfg_scale:         7.00
    clip_skip:         -1
    width:             512
    height:            512
    sample_method:     euler_a
    schedule:          default
    sample_steps:      20
    strength(img2img): 0.75
    rng:               cuda
    seed:              42
    batch_count:       1
    vae_tiling:        false
System Info: 
    BLAS = 1
    SSE3 = 0
    AVX = 0
    AVX2 = 0
    AVX512 = 0
    AVX512_VBMI = 0
    AVX512_VNNI = 0
    FMA = 0
    NEON = 1
    ARM_FMA = 1
    F16C = 0
    FP16_VA = 1
    WASM_SIMD = 0
    VSX = 0
[DEBUG] stable-diffusion.cpp:6095 - Using CPU backend
[INFO]  stable-diffusion.cpp:6105 - loading model from '../models/sd-v1-4.ckpt'
[INFO]  model.cpp:641  - load ../models/sd-v1-4.ckpt using checkpoint format
[DEBUG] model.cpp:1142 - init from '../models/sd-v1-4.ckpt'
[INFO]  stable-diffusion.cpp:6131 - Stable Diffusion 1.x 
[INFO]  stable-diffusion.cpp:6137 - Stable Diffusion weight type: f16
[DEBUG] stable-diffusion.cpp:6139 - loading vocab
[DEBUG] stable-diffusion.cpp:739  - vocab size: 49408
[DEBUG] stable-diffusion.cpp:6149 - ggml tensor size = 384 bytes
[DEBUG] stable-diffusion.cpp:1510 - clip params backend buffer size =  236.18 MB (449 tensors)
[DEBUG] stable-diffusion.cpp:2527 - unet params backend buffer size =  1650.16 MB (720 tensors)
[DEBUG] stable-diffusion.cpp:3586 - vae params backend buffer size =  95.47 MB (164 tensors)
[DEBUG] stable-diffusion.cpp:6166 - preparing memory for the weights
[DEBUG] stable-diffusion.cpp:6198 - loading weights
[DEBUG] model.cpp:1224 - loading tensors from ../models/sd-v1-4.ckpt
[DEBUG] stable-diffusion.cpp:6286 - model size = 1969.67MB
[INFO]  stable-diffusion.cpp:6296 - total memory buffer size = 1981.80MB (clip 236.18MB, unet 1650.16MB, vae 95.47MB)
[INFO]  stable-diffusion.cpp:6298 - loading model from '../models/sd-v1-4.ckpt' completed, taking 9.97s
[INFO]  stable-diffusion.cpp:6312 - running in eps-prediction mode
[DEBUG] stable-diffusion.cpp:6339 - finished loaded file
[INFO]  stable-diffusion.cpp:5334 - loading control net from 'models/control_openpose-fp16.safetensors'
[INFO]  model.cpp:638  - load models/control_openpose-fp16.safetensors using safetensors format
[DEBUG] model.cpp:704  - init from 'models/control_openpose-fp16.safetensors'
[DEBUG] stable-diffusion.cpp:5263 - control net params backend buffer size =  693.43 MB (347 tensors)
[DEBUG] model.cpp:1224 - loading tensors from models/control_openpose-fp16.safetensors
[INFO]  stable-diffusion.cpp:5402 - control net model loaded
[DEBUG] stable-diffusion.cpp:7218 - prompt after extract and remove lora: "a person"
[INFO]  stable-diffusion.cpp:7223 - apply_loras completed, taking 0.00s
[DEBUG] stable-diffusion.cpp:1457 - parse 'a person' to [['a person', 1], ]
[DEBUG] stable-diffusion.cpp:889  - split prompt "a person" to tokens ["a</w>", "person</w>", ]
[DEBUG] stable-diffusion.cpp:1624 - learned condition compute buffer size: 2.58 MB
[DEBUG] stable-diffusion.cpp:6462 - computing condition graph completed, taking 40 ms
[DEBUG] stable-diffusion.cpp:1457 - parse '' to [['', 1], ]
[DEBUG] stable-diffusion.cpp:889  - split prompt "" to tokens []
[DEBUG] stable-diffusion.cpp:1624 - learned condition compute buffer size: 2.58 MB
[DEBUG] stable-diffusion.cpp:6462 - computing condition graph completed, taking 38 ms
[INFO]  stable-diffusion.cpp:7262 - get_learned_condition completed, taking 80 ms
[INFO]  stable-diffusion.cpp:7278 - sampling using Euler A method
[INFO]  stable-diffusion.cpp:7282 - generating image: 1/1 - seed 42
[DEBUG] stable-diffusion.cpp:5616 - controlnet compute buffer size: 547.79 MB -> 13 control output tensors
[DEBUG] stable-diffusion.cpp:2894 - diffusion compute buffer size: 559.71 MB
  |>                                                 | 0/20 - 0.00it/s[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |==>                                               | 1/20 - 4.14s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |=====>                                            | 2/20 - 3.96s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |=======>                                          | 3/20 - 3.95s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |==========>                                       | 4/20 - 4.00s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |============>                                     | 5/20 - 3.96s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |===============>                                  | 6/20 - 4.04s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |=================>                                | 7/20 - 4.00s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |====================>                             | 8/20 - 3.86s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |======================>                           | 9/20 - 4.01s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |=========================>                        | 10/20 - 3.96s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |===========================>                      | 11/20 - 4.00s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |==============================>                   | 12/20 - 3.96s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |================================>                 | 13/20 - 3.90s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |===================================>              | 14/20 - 3.92s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |=====================================>            | 15/20 - 3.94s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |========================================>         | 16/20 - 4.02s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |==========================================>       | 17/20 - 4.00s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |=============================================>    | 18/20 - 3.87s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |===============================================>  | 19/20 - 3.95s/it[DEBUG] stable-diffusion.cpp:6606 - control net start
[DEBUG] stable-diffusion.cpp:6608 - control net end
  |==================================================| 20/20 - 4.00s/it
[INFO]  stable-diffusion.cpp:7294 - sampling completed, taking 79.55s
[INFO]  stable-diffusion.cpp:7302 - generating 1 latent images completed, taking 79.57s
[INFO]  stable-diffusion.cpp:7304 - decoding 1 latents
[DEBUG] stable-diffusion.cpp:3717 - vae compute buffer size: 1664.00 MB
[DEBUG] stable-diffusion.cpp:7113 - computing vae [mode: DECODE] graph completed, taking 5.24s
[INFO]  stable-diffusion.cpp:7314 - latent 1 decoded, taking 5.24s
[INFO]  stable-diffusion.cpp:7318 - decode_first_stage completed, taking 5.24s
[INFO]  stable-diffusion.cpp:7335 - txt2img completed in 84.90s
[INFO]  main.cpp:541  - save result image to 'output.png'
```
</details>

**Comment by FSSRepo** [comment]
Try running it in debug mode.

**Comment by FSSRepo** [comment]
@ggerganov  It was a variable that was causing an overflow. With debug mode, I managed to detect it, although NaNs (Not a Number) are still being generated somewhere in the computation graph, anyway thank you for your time. I am going to check.

**Comment by FSSRepo** [comment]
@ggerganov Is what I'm doing correct when extracting data from collected tensors into a vector? I suspect I might be reading a memory address with residual data.

**Comment by FSSRepo** [comment]
@leejet can you test this?

**Comment by leejet** [comment]
> @leejet can you test this?

@FSSRepo Where did you download the ControlNet model from? When I used the official provided weights from https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main, the tensor names didn't match.

**Comment by FSSRepo** [comment]
@leejet this is controlnet v1.0 f16 models, [link](https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main)

**Comment by FSSRepo** [comment]
@leejet those pth models have the prefix `control_model.` that's why they have invalid names.

**Comment by leejet** [comment]
> @leejet Control Net for stable diffusion 1.5:
> 
> [Control Net v1](https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main) [Control Net v1.1](https://huggingface.co/F16/ControlNet-v1-1_f16/tree/main)

It looks like ControlNet is in effect.

```
.\bin\Release\sd.exe -m ..\..\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors -p "a person" --control-net  ..\models\control_openpose-fp16.safetensors  --control-image ..\assets\control.png -v
```

output

**Comment by Amin456789** [comment]
omg, u guys are bringing everything to sd cpp! thank u for all ur hard work, can't wait for inpainting and outpainting too be a part of controlnet

**Comment by FSSRepo** [comment]
@leejet Ready, the official pth models should also be working now. I should emphasize that they also include other t2i models; those are a different architecture. They make changes to the input blocks, while ControlNet makes changes to the output blocks and the middle block.

**Comment by leejet** [comment]
Great job, and thank you for your contributions. I'll find some time to review and merge this PR.

**Comment by FSSRepo** [comment]
@leejet All working correctly

**Comment by Green-Sky** [comment]
@FSSRepo you can remove the async+sync cuda hack when https://github.com/ggerganov/ggml/pull/679 gets merged.

**Comment by FSSRepo** [comment]
@Green-Sky Does it also solve the VAE tiling problem?

**Comment by FSSRepo** [comment]
@Green-Sky Could you try this pull request if it works correctly for you? Also, if you try removing this #ifdef.

```c++
__STATIC_INLINE__ void ggml_backend_tensor_get_and_sync(ggml_backend_t backend, const struct ggml_tensor* tensor, void* data, size_t offset, size_t size) {
  // delete this to use just ggml_backend_tensor_get
#ifdef SD_USE_CUBLAS
    if(!ggml_backend_is_cpu(backend)) {
        ggml_backend_tensor_get_async(backend, tensor, data, offset, size);
        ggml_backend_synchronize(backend);
    } else {
        ggml_backend_tensor_get(tensor, data, offset, size);
    }
#else
    ggml_backend_tensor_get(tensor, data, offset, size);
#endif
}
```

with and without vae tiling

**Comment by Jonathhhan** [comment]
@FSSRepo control net works very well for the first image after the model was loaded. Is it possible to make it work for more than one image?

**Comment by Green-Sky** [comment]
> @Green-Sky Does it also solve the VAE tiling problem?

which one? the neony artifacts or the "some tiles look lower resolution" ?


I ran the branch rn and it appears the tiling is not executed? despite it being set.

```
    vae_tiling:        true
```

```
[DEBUG] ggml_extend.hpp:603  - clip compute buffer size: 2.58 MB
[DEBUG] stable-diffusion.cpp:460  - computing condition graph completed, taking 8 ms
[INFO ] stable-diffusion.cpp:1266 - get_learned_condition completed, taking 28 ms
[INFO ] stable-diffusion.cpp:1282 - sampling using Euler A method
[INFO ] stable-diffusion.cpp:1286 - generating image: 1/1 - seed 42
[DEBUG] ggml_extend.hpp:603  - unet compute buffer size: 2137.25 MB
  |==================================================| 20/20 - 1.11it/s
[INFO ] stable-diffusion.cpp:1298 - sampling completed, taking 18.37s
[INFO ] stable-diffusion.cpp:1306 - generating 1 latent images completed, taking 18.37s
[INFO ] stable-diffusion.cpp:1308 - decoding 1 latents
[DEBUG] ggml_extend.hpp:603  - vae compute buffer size: 3329.00 MB
[DEBUG] stable-diffusion.cpp:1111 - computing vae [mode: DECODE] graph completed, taking 1.49s
[INFO ] stable-diffusion.cpp:1318 - latent 1 decoded, taking 1.49s
[INFO ] stable-diffusion.cpp:1322 - decode_first_stage completed, taking 1.49s
[INFO ] stable-diffusion.cpp:1339 - txt2img completed in 19.89s
```

... if however I am wrong and the tiling is executed, then it's perfect now. Even the seams would be gone.

**Comment by FSSRepo** [comment]
@Green-Sky you can try again

**Comment by FSSRepo** [comment]
@Green-Sky you can try again

**Comment by Green-Sky** [comment]
toggling this section does not make a difference:
```
#ifdef SD_USE_CUBLAS
    if(!ggml_backend_is_cpu(backend)) {
        ggml_backend_tensor_get_async(backend, tensor, data, offset, size);
        ggml_backend_synchronize(backend);
    } else {
        ggml_backend_tensor_get(tensor, data, offset, size);
    }
#else
    ggml_backend_tensor_get(tensor, data, offset, size);
#endif
```

as is:
output_4

without:
output_4


at least it looks like it deterministic. (besides github deciding randomly how large an image is displayed/processed)

**Comment by Green-Sky** [comment]
also, if the tiles are overlapped, no steams should be visible.
(weak src: https://github.com/madebyollin/taesd/issues/8#issuecomment-1675992525 )

**Comment by FSSRepo** [comment]
When conducting tests, I am also obtaining results that seem to be of low resolution. I'm not sure what the cause might be.

**Comment by Jonathhhan** [comment]
Segmentation with `control_seg-fp16` is also working very well.


seg


Screenshot 2024-01-06 005456

**Comment by Jonathhhan** [comment]
> The missing part is to create the preprocessors. But that is cumbersome and somewhat complicated, as it requires implementing other models (image2depth and openpose) and algorithms to perform Canny (edge detection).

Not sure, if this is of any help. But I tried to do canny edge detection with `openCv` and it works quite well.
This is the code that I use for Open Frameworks:
```
						image.load(result.getPath());
						int lowThreshold = 50;
						const int max_lowThreshold = 100;
						const int ratio = 3;
						const int kernel_size = 3;
						cv::Mat src, src_gray;
						cv::Mat detected_edges;
						src = ofxCv::toCv(image);
						cv::cvtColor(src, src_gray, cv::COLOR_BGR2GRAY);
						cv::blur(src_gray, detected_edges, cv::Size(3, 3));
						cv::Canny(detected_edges, detected_edges, lowThreshold, lowThreshold* ratio, kernel_size);
						ofxCv::toOf(detected_edges, image);
						image.update();
```
And here a general example: https://docs.opencv.org/4.x/da/d5c/tutorial_canny_detector.html

**Comment by FSSRepo** [comment]
That implies using very heavy libraries that are not really necessary for the functioning of this project itself; it's better to have it integrated from scratch in ggml.

**Comment by Jonathhhan** [comment]
> That implies using very heavy libraries that are not really necessary for the functioning of this project itself; it's better to have it integrated from scratch in ggml.

True (at least `sam.cpp` works with `ggml`, but `SamAutomaticMaskGenerator`, which is needed for segmenting, is not part of `sam.cpp` yet).

**Comment by leejet** [comment]
In the past few weeks, I have been busy with pull requests related to svd, so I didn't have a chance to merge this PR. Now that I've addressed some issues, I'm ready to merge this PR. Thank you for your contribution.

**Comment by FSSRepo** [comment]
@leejet Thank you for continuing to maintain the project despite having other jobs. I'll see if in the next few days, when I have time to implement flash attention in llama.cpp, I can adapt the web UI that I already have created to the project.

**Comment by pwillia7** [comment]
Would controlnet with SDXL work with this update?

**Comment by rootgrandfather** [comment]
I ran the above command and got the following error message, can anyone help me?

root@c-66fe0199-152fc2e0-851f6bf93291:/tmp# ./sd --mode txt2img -p "a person" -m /mnt/auto/sd-v1-4.ckpt --control-net /mnt/auto/sd/control_openpose-fp16.safetensors  --control-image /mnt/auto/sd/openposeimg.png  --control-net-cpu
[INFO ] stable-diffusion.cpp:195  - loading model from '/mnt/auto/sd-v1-4.ckpt'
[INFO ] model.cpp:796  - load /mnt/auto/sd-v1-4.ckpt using checkpoint format
[INFO ] stable-diffusion.cpp:235  - Version: SD 1.x 
[INFO ] stable-diffusion.cpp:266  - Weight type:                 f32
[INFO ] stable-diffusion.cpp:267  - Conditioner weight type:     f32
[INFO ] stable-diffusion.cpp:268  - Diffusion model weight type: f32
[INFO ] stable-diffusion.cpp:269  - VAE weight type:             f32
[INFO ] control.hpp:434  - loading control net from '/mnt/auto/sd/control_openpose-fp16.safetensors'
[INFO ] model.cpp:793  - load /mnt/auto/sd/control_openpose-fp16.safetensors using safetensors format
[INFO ] control.hpp:453  - control net model loaded
[INFO ] stable-diffusion.cpp:482  - total params memory size = 3656.84MB (VRAM 937.60MB, RAM 2719.24MB): clip 469.44MB(RAM), unet 2155.33MB(RAM), vae 94.47MB(RAM), controlnet 937.60MB(VRAM), pmid 0.00MB(RAM)
[INFO ] stable-diffusion.cpp:501  - loading model from '/mnt/auto/sd-v1-4.ckpt' completed, taking 15.44s
[INFO ] stable-diffusion.cpp:528  - running in eps-prediction mode
[INFO ] stable-diffusion.cpp:655  - Attempting to apply 0 LoRAs
[INFO ] stable-diffusion.cpp:1132 - apply_loras completed, taking 0.00s
[INFO ] stable-diffusion.cpp:1256 - get_learned_condition completed, taking 448 ms
[INFO ] stable-diffusion.cpp:1279 - sampling using Euler A method
[INFO ] stable-diffusion.cpp:1283 - generating image: 1/1 - seed 42
/root/software/stable-diffusion.cpp-build/build/_deps/sd-src/ggml/src/ggml.c:4508: GGML_ASSERT(ggml_can_repeat(b, a)) failed
./sd(+0x1597db)[0x5570d32957db]
./sd(+0x15b821)[0x5570d3297821]
./sd(+0x181258)[0x5570d32bd258]
./sd(+0xea1e2)[0x5570d32261e2]
./sd(+0xec054)[0x5570d3228054]
./sd(+0xacbe5)[0x5570d31e8be5]
./sd(+0xb78e5)[0x5570d31f38e5]
./sd(+0xc21d0)[0x5570d31fe1d0]
./sd(+0xa15ea)[0x5570d31dd5ea]
./sd(+0xa3368)[0x5570d31df368]
./sd(+0x1aed7)[0x5570d3156ed7]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0)[0x7f92772aafd0]
/usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)[0x7f92772ab07d]
./sd(+0x22f55)[0x5570d315ef55]
Aborted (core dumped)

root@c-66fe0199-152fc2e0-851f6bf93291:/tmp# ./sd --mode txt2img -p "a person" -m /mnt/auto/sd-v1-4.ckpt --control-net /mnt/auto/sd/control_openpose-fp16.safetensors  --control-image /mnt/auto/sd/openposeimg.png  --control-net-cpu --type f16 -v
Option: 
    n_threads:         4
    mode:              txt2img
    model_path:        /mnt/auto/sd-v1-4.ckpt
    wtype:             f16
    clip_l_path:       
    t5xxl_path:        
    diffusion_model_path:   
    vae_path:          
    taesd_path:        
    esrgan_path:       
    controlnet_path:   /mnt/auto/sd/control_openpose-fp16.safetensors
    embeddings_path:   
    stacked_id_embeddings_path:   
    input_id_images_path:   
    style ratio:       20.00
    normalize input image :  false
    output_path:       output.png
    init_img:          
    control_image:     /mnt/auto/sd/openposeimg.png
    clip on cpu:       false
    controlnet cpu:    true
    vae decoder on cpu:false
    strength(control): 0.90
    prompt:            a person
    negative_prompt:   
    min_cfg:           1.00
    cfg_scale:         7.00
    guidance:          3.50
    clip_skip:         -1
    width:             512
    height:            512
    sample_method:     euler_a
    schedule:          default
    sample_steps:      20
    strength(img2img): 0.75
    rng:               cuda
    seed:              42
    batch_count:       1
    vae_tiling:        false
    upscale_repeats:   1
System Info: 
    BLAS = 0
    SSE3 = 1
    AVX = 1
    AVX2 = 1
    AVX512 = 1
    AVX512_VBMI = 0
    AVX512_VNNI = 0
    FMA = 1
    NEON = 0
    ARM_FMA = 0
    F16C = 1
    FP16_VA = 0
    WASM_SIMD = 0
    VSX = 0
[DEBUG] stable-diffusion.cpp:180  - Using CPU backend
[INFO ] stable-diffusion.cpp:195  - loading model from '/mnt/auto/sd-v1-4.ckpt'
[INFO ] model.cpp:796  - load /mnt/auto/sd-v1-4.ckpt using checkpoint format
[DEBUG] model.cpp:1320 - init from '/mnt/auto/sd-v1-4.ckpt'
[INFO ] stable-diffusion.cpp:235  - Version: SD 1.x 
[INFO ] stable-diffusion.cpp:266  - Weight type:                 f16
[INFO ] stable-diffusion.cpp:267  - Conditioner weight type:     f16
[INFO ] stable-diffusion.cpp:268  - Diffusion model weight type: f16
[INFO ] stable-diffusion.cpp:269  - VAE weight type:             f16
[DEBUG] stable-diffusion.cpp:271  - ggml tensor size = 400 bytes
[DEBUG] clip.hpp:171  - vocab size: 49408
[DEBUG] clip.hpp:182  -  trigger word img already in vocab
[DEBUG] ggml_extend.hpp:1046 - clip params backend buffer size =  235.06 MB(RAM) (196 tensors)
[DEBUG] ggml_extend.hpp:1046 - unet params backend buffer size =  1640.25 MB(RAM) (686 tensors)
[DEBUG] ggml_extend.hpp:1046 - vae params backend buffer size =  94.47 MB(RAM) (140 tensors)
[DEBUG] stable-diffusion.cpp:398  - loading weights
[DEBUG] model.cpp:1530 - loading tensors from /mnt/auto/sd-v1-4.ckpt
[INFO ] control.hpp:434  - loading control net from '/mnt/auto/sd/control_openpose-fp16.safetensors'
[DEBUG] ggml_extend.hpp:1046 - control_net params backend buffer size =  689.48 MB(RAM) (340 tensors)
[INFO ] model.cpp:793  - load /mnt/auto/sd/control_openpose-fp16.safetensors using safetensors format
[DEBUG] model.cpp:861  - init from '/mnt/auto/sd/control_openpose-fp16.safetensors'
[DEBUG] model.cpp:1530 - loading tensors from /mnt/auto/sd/control_openpose-fp16.safetensors
[INFO ] control.hpp:453  - control net model loaded
[INFO ] stable-diffusion.cpp:482  - total params memory size = 2659.26MB (VRAM 689.48MB, RAM 1969.78MB): clip 235.06MB(RAM), unet 1640.25MB(RAM), vae 94.47MB(RAM), controlnet 689.48MB(VRAM), pmid 0.00MB(RAM)
[INFO ] stable-diffusion.cpp:501  - loading model from '/mnt/auto/sd-v1-4.ckpt' completed, taking 15.38s
[INFO ] stable-diffusion.cpp:528  - running in eps-prediction mode
[DEBUG] stable-diffusion.cpp:572  - finished loaded file
[DEBUG] stable-diffusion.cpp:1378 - txt2img 512x619
[DEBUG] stable-diffusion.cpp:1127 - prompt after extract and remove lora: "a person"
[INFO ] stable-diffusion.cpp:655  - Attempting to apply 0 LoRAs
[INFO ] stable-diffusion.cpp:1132 - apply_loras completed, taking 0.00s
[DEBUG] conditioner.hpp:325  - parse 'a person' to [['a person', 1], ]
[DEBUG] clip.hpp:311  - token length: 77
[DEBUG] ggml_extend.hpp:998  - clip compute buffer size: 1.40 MB(RAM)
[DEBUG] conditioner.hpp:453  - computing condition graph completed, taking 148 ms
[DEBUG] conditioner.hpp:325  - parse '' to [['', 1], ]
[DEBUG] clip.hpp:311  - token length: 77
[DEBUG] ggml_extend.hpp:998  - clip compute buffer size: 1.40 MB(RAM)
[DEBUG] conditioner.hpp:453  - computing condition graph completed, taking 145 ms
[INFO ] stable-diffusion.cpp:1256 - get_learned_condition completed, taking 295 ms
[INFO ] stable-diffusion.cpp:1279 - sampling using Euler A method
[INFO ] stable-diffusion.cpp:1283 - generating image: 1/1 - seed 42
/root/software/stable-diffusion.cpp-build/build/_deps/sd-src/ggml/src/ggml.c:4508: GGML_ASSERT(ggml_can_repeat(b, a)) failed
./sd(+0x1597db)[0x5565d2f8d7db]
./sd(+0x15b821)[0x5565d2f8f821]
./sd(+0x181258)[0x5565d2fb5258]
./sd(+0xea1e2)[0x5565d2f1e1e2]
./sd(+0xec054)[0x5565d2f20054]
./sd(+0xacbe5)[0x5565d2ee0be5]
./sd(+0xb78e5)[0x5565d2eeb8e5]
./sd(+0xc21d0)[0x5565d2ef61d0]
./sd(+0xa15ea)[0x5565d2ed55ea]
./sd(+0xa3368)[0x5565d2ed7368]
./sd(+0x1aed7)[0x5565d2e4eed7]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0)[0x7f146d7d0fd0]
/usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)[0x7f146d7d107d]
./sd(+0x22f55)[0x5565d2e56f55]
Aborted (core dumped)

**Pull request merged**
