### PR TITLE
Refact process flow + Fix img2vid mode + Provide abilities to img2img mode

### PR DESCRIPTION
**Pull request by Windsander**
reference to this one:

https://github.com/leejet/stable-diffusion.cpp/pull/210

recreate from this one... cuase by  my stupid click..

https://github.com/leejet/stable-diffusion.cpp/pull/210#issue-2215243716

**What this commit done**

-- New features:
1. Now img2vid is available on sd.cpp
2. RealESRGAN_x4plus_anime_6B for each mode output, is supported
3. Image + Text Prompts(positive/negative) now is supported for each mode

-- Core abilities been added to sd.cpp img2img mode:
1. Provide LoRA support
2. Provide ControlNet support
3. Provide PhotoMaker embeddings available

-- Refact sd_context lifecycle with ggml_context maintain:
1. Make ggml_context retainable for continuous using
2. Reconfig ggml_context only on necessary, like prompt recreate etc.
3.Devide SD_core models workflow from prompt preprocess & embedding flow

**What SVD-XT(img2vid) abilities has**

1. support <prompt + negative-prompt>
2. support embedding with init-image
3. support  as start spatial-info, which we familiar as Image-prompt
4. support with LoRAs help.
5. support with PhotoMaker.

**Which been tested by 7 cases below (only params):**

**img2img**
```bash
 #test case: img2img<sdxl,sdxl-vae>
 -p " best quality, extremely detailed, only main character, keep background scene, portrait of girl " -n " every characters, change background scene, worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet, extra feet " --model ../../../sd-models/sd_xl_turbo_1.0_fp16.safetensors --vae ../../../sd-models/sdxl_vae.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 3 --cfg-scale 1.0 --seed 15.0 -M img2img -H 1024 -W 1024 -i ../../../io-test/input.png -o ../../../io-test/output.png -v

 #test case: img2img<sdxl,sdxl-vae,lcm-lora>
 -p " best quality, extremely detailed, keep main character<lora:lcm-lora-sdxl:1>, at night with stars " -n " worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet, extra feet " --lora-model-dir ../../../sd-control-lora/control-LoRAs-lcm --model ../../../sd-models/sd_xl_turbo_1.0_fp16.safetensors --vae ../../../sd-models/sdxl_vae.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 3 --cfg-scale 1.0 --seed 15.0 -M img2img -H 1024 -W 1024 -i ../../../io-test/input.png -o ../../../io-test/output.png -v

 #test case: img2img<sdv1.5, sdv1.5-vae, lcm-lora, control_net>
 -p " best quality, extremely detailed, keep main character<lora:lcm-lora-sdv1-5:1>, at night with stars " -n " worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet, extra feet " --control-net ../../../sd-control-net/sdv1_5/control_v11p_sd15_canny_2.safetensors --lora-model-dir ../../../sd-control-lora/control-LoRAs-lcm --model ../../../sd-models/v1-5-pruned-emaonly.safetensors --vae ../../../sd-models/diffusion_pytorch_model.fp16.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 3 --cfg-scale 1.0 --seed 15.0 -M img2img -H 1024 -W 1024 --control-image ../../../io-test/input_canny_mask.png -i ../../../io-test/input.png -o ../../../io-test/output.png -v

```

**txt2img**
```bash
 #test case: txt2img<sdxl,sdxl-vae>
 -p " best quality, extremely detailed, only main character, keep background scene, portrait of girl " -n " every characters, change background scene, worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet, extra feet " --model ../../../sd-models/sd_xl_turbo_1.0_fp16.safetensors --vae ../../../sd-models/sdxl_vae.safetensors --sampling-method lcm --style-ratio 10 --steps 20 --cfg-scale 1.0 --seed 15.0 -M txt2img -H 1024 -W 1024 -o ../../../io-test/output.png -v

 #test case: txt2img<sdxl,sdxl-vae,lcm-lora>
 -p " best quality, extremely detailed, keep main character<lora:lcm-lora-sdxl:1>, at night with stars " -n " worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet, extra feet " --lora-model-dir ../../../sd-control-lora/control-LoRAs-lcm --model ../../../sd-models/sd_xl_turbo_1.0_fp16.safetensors --vae ../../../sd-models/sdxl_vae.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 40 --cfg-scale 1.0 --seed 15.0 -M txt2img -H 1024 -W 1024 -o ../../../io-test/output.png -v

 #test case: txt2img<sdv1.5, sdv1.5-vae, lcm-lora, control_net(canny)>
-p " best quality, extremely detailed, keep main character<lora:lcm-lora-sdv1-5:1>, at night with stars " -n " worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet, extra feet " --type f16 --control-net ../../../sd-control-net/sdv1_5/control_v11p_sd15_canny_2.safetensors --lora-model-dir ../../../sd-control-lora/control-LoRAs-lcm --model ../../../sd-models/v1-5-pruned-emaonly.safetensors --vae ../../../sd-models/diffusion_pytorch_model.fp16.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 60 --cfg-scale 1.0 --seed 15.0 -M txt2img -H 1024 -W 1024 --control-image ../../../io-test/input_canny_mask.png -o ../../../io-test/output.png -v
 ```
 
**img2vid**
```bash
  #test case: img2vid<svd-xt, svd-xt-vae>
 -p " best quality, extremely detailed, keep main character, in outer space " -n " worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet, extra feet " --model ../../../sd-video/svd_xt.safetensors --vae ../../../sd-video/vae/diffusion_pytorch_model.fp16.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 3 --cfg-scale 1.0 --seed 15.0 -M img2vid -H 1024 -W 1024 --video-total-frames 14 --video-fps 14 --motion-bucket-id 42 -i ../../../io-test/input.png -o ../../../io-test/output.png -v
 
  #test case: img2vid<svd-xt, svd-xt-vae>(no negative-prompt)
 -p " best quality, extremely detailed, keep main character, in outer space " --model ../../../sd-video/svd_xt.safetensors --vae ../../../sd-video/vae/diffusion_pytorch_model.fp16.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 3 --cfg-scale 1.0 --seed 15.0 -M img2vid -H 1024 -W 1024 --video-total-frames 14 --video-fps 8 --motion-bucket-id 42 -i ../../../io-test/input.png -o ../../../io-test/output.png -v
```

 **Test model version:**
 8201711714129_ pic

### CODE REVIEW

**Comment by Windsander** [comment]
> god... wrong click...



> I'm using the sd official :
> 
> https://huggingface.co/stabilityai/stable-video-diffusion-img2vid
> 
> with prompt:
> 
> -p " best quality, extremely detailed, keep main character, in outer space " --model ../../../sd-video/svd_xt.safetensors --vae ../../../sd-video/vae/diffusion_pytorch_model.fp16.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 3 --cfg-scale 1.0 --seed 15.0 -M img2vid -H 1024 -W 1024 --video-total-frames 14 --video-fps 8 --motion-bucket-id 42 -i ../../../io-test/input.png -o ../../../io-test/output.png -v

use this T_T sorry..

**Comment by Windsander** [comment]
image

**Comment by Windsander** [comment]
image

**Comment by Green-Sky** [comment]
your command line, or close to it, just crashes for me:
```
$ result/bin/sd -m models/svd_xt.safetensors -p "best quality, extremely detailed, keep main character, in outer space" --vae models/diffusion_pytorch_model.fp16.safetensors --steps 3 --cfg-scale 1.0 -M img2vid -H 1024 -W 1024 --video-total-frames 14 --video-fps 8 --motion-bucket-id 42 -i input.png --strength 0.65 --style-ratio 10
resize input image from 768x768 to 1024x1024
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2070, compute capability 7.5, VMM: yes
[INFO ] stable-diffusion.cpp:228  - loading model from 'models/svd_xt.safetensors'
[INFO ] model.cpp:750  - load models/svd_xt.safetensors using safetensors format
[INFO ] stable-diffusion.cpp:239  - loading vae from 'models/diffusion_pytorch_model.fp16.safetensors'
[INFO ] model.cpp:750  - load models/diffusion_pytorch_model.fp16.safetensors using safetensors format
[INFO ] stable-diffusion.cpp:251  - Stable Diffusion SVD
[INFO ] stable-diffusion.cpp:257  - Stable Diffusion weight type: f32
[ERROR] clip.hpp:701  - transpose_weight
[ERROR] clip.hpp:701  - transpose_weight
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 4438.18 MiB on device 0: cudaMalloc failed: out of memory
alloc_tensor_range: failed to allocate CUDA0 buffer of size 4653768832
[ERROR] ggml_extend.hpp:876  - unet alloc params backend buffer failed
[ERROR] clip.hpp:701  - transpose_weight
[ERROR] clip.hpp:701  - transpose_weight
[INFO ] model.cpp:1534 - unknown tensor 'cond_stage_model.model.logit_scale | f32 | 0 [1, 1, 1, 1, 1]' in model file
Segmentation fault (core dumped)
```

i suspected f32 to be the cause, so i tried f16, which got further:
```
$ result/bin/sd -m models/svd_xt.safetensors -p "best quality, extremely detailed, keep main character, in outer space" --vae models/diffusion_pytorch_model.fp16.safetensors --steps 3 --cfg-scale 1.0 -M img2vid -H 1024 -W 1024 --video-total-frames 14 --video-fps 8 --motion-bucket-id 42 -i input.png --strength 0.65 --style-ratio 10 --type f16
resize input image from 768x768 to 1024x1024
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2070, compute capability 7.5, VMM: yes
[INFO ] stable-diffusion.cpp:228  - loading model from 'models/svd_xt.safetensors'
[INFO ] model.cpp:750  - load models/svd_xt.safetensors using safetensors format
[INFO ] stable-diffusion.cpp:239  - loading vae from 'models/diffusion_pytorch_model.fp16.safetensors'
[INFO ] model.cpp:750  - load models/diffusion_pytorch_model.fp16.safetensors using safetensors format
[INFO ] stable-diffusion.cpp:251  - Stable Diffusion SVD
[INFO ] stable-diffusion.cpp:257  - Stable Diffusion weight type: f16
[ERROR] clip.hpp:701  - transpose_weight
[ERROR] clip.hpp:701  - transpose_weight
[ERROR] clip.hpp:701  - transpose_weight
[ERROR] clip.hpp:701  - transpose_weight
[INFO ] model.cpp:1534 - unknown tensor 'cond_stage_model.model.logit_scale | f32 | 0 [1, 1, 1, 1, 1]' in model file
[INFO ] model.cpp:1534 - unknown tensor 'first_stage_model.decoder.conv_out.time_conv_out.bias | f16 | 1 [3, 1, 1, 1, 1]' in model file
[INFO ] model.cpp:1534 - unknown tensor 'first_stage_model.decoder.conv_out.time_conv_out.weight | f16 | 4 [1, 3, 3, 3, 1]' in model file
[INFO ] stable-diffusion.cpp:446  - total params memory size = 4402.57MB (VRAM 4402.57MB, RAM 0.00MB): clip 1306.05MB(VRAM), unet 2909.90MB(VRAM), vae 186.62MB(VRAM), controlnet 0.00MB(VRAM), pmid 0.00MB(VRAM)
[INFO ] stable-diffusion.cpp:465  - loading model from 'models/svd_xt.safetensors' completed, taking 3.25s
[INFO ] stable-diffusion.cpp:480  - running in v-prediction mode
[INFO ] stable-diffusion.cpp:2425 - ===========================<img2vid>===========================
[INFO ] stable-diffusion.cpp:2426 - <img2vid> start
[INFO ] stable-diffusion.cpp:2429 - <img2vid> encode_first_stage start
[INFO ] stable-diffusion.cpp:1592 - output size 1024x1024
[INFO ] stable-diffusion.cpp:1595 - update ggml_context with img_size 1024 x 1024
ggml_aligned_malloc: insufficient memory (attempted to allocate 56024.00 MB)
GGML_ASSERT: /build/2ins26ihh2rdq41jqf7sqrcwi7pdwb1b-source/ggml/src/ggml.c:224: false
```

so I used 512x512 instead:
```
[INFO ] stable-diffusion.cpp:446  - total params memory size = 4402.57MB (VRAM 4402.57MB, RAM 0.00MB): clip 1306.05MB(VRAM), unet 2909.90MB(VRAM), vae 186.62MB(VRAM), controlnet 0.00MB(VRAM), pmid 0.00MB(VRAM)
[INFO ] stable-diffusion.cpp:465  - loading model from 'models/svd_xt.safetensors' completed, taking 2.91s
[INFO ] stable-diffusion.cpp:480  - running in v-prediction mode
[INFO ] stable-diffusion.cpp:2425 - ===========================<img2vid>===========================
[INFO ] stable-diffusion.cpp:2426 - <img2vid> start
[INFO ] stable-diffusion.cpp:2429 - <img2vid> encode_first_stage start
[INFO ] stable-diffusion.cpp:1592 - output size 512x512
[INFO ] stable-diffusion.cpp:1595 - update ggml_context with img_size 512 x 512
[INFO ] stable-diffusion.cpp:1603 - update ggml_context success, current mem_size 1969225728
[INFO ] stable-diffusion.cpp:1611 - target t_enc is 1 steps
[INFO ] stable-diffusion.cpp:1617 - sigma scheduler completed, taking 0.00s
[INFO ] stable-diffusion.cpp:1650 - current batch count set to: 1
[INFO ] stable-diffusion.cpp:1659 - config_control_net() with NULL control_image, ControlNet disabled
[INFO ] stable-diffusion.cpp:1685 - config_photo_maker() with NULL reference_images, PhotoMaker disabled
[INFO ] stable-diffusion.cpp:595  - Attempting to apply 0 LoRAs
[INFO ] stable-diffusion.cpp:1852 - apply_loras completed, taking 0.00s
ggml_gallocr_reserve_n: reallocating CUDA0 buffer from size 0.00 MiB to 11.18 MiB
ggml_backend_cuda_graph_compute: error: op not supported node_1344 (OUT_PROD)
GGML_ASSERT: /build/2ins26ihh2rdq41jqf7sqrcwi7pdwb1b-source/ggml/src/ggml-cuda.cu:12277: ok
```
which seems to assert an op type.

Am I stupid for trying this on cuda? :laughing:

**Comment by Green-Sky** [comment]
I am now running it on cpu, I also had to drop to 256x256, because 512x512 is consuming over 32GiB of ram (my max). Even 256x256 is consuming over 14GiB of ram, so there are probably memory efficiencies still on the table. :smile: 

Will post the results when its done.

**Comment by Green-Sky** [comment]
output
(first frame)
They all look kind of like this, probably because I only used 3 steps and cfgscale 1 and 256x256, but it seems to be semi stable garble. :partying_face:

**Comment by Windsander** [comment]
> output (first frame) They all look kind of like this, probably because I only used 3 steps and cfgscale 1 and 256x256, but it seems to be semi stable garble. 🥳
> 
>  svd-xt_first_try_s3_cfg1_256.mp4

yep :p

I'm running on Mac M2...  so it only have CPU mode(cause Metal on ggml seems not stable 0_0 )

the reason cause frames like that is steps using 3. in svd-xt suggest setting larger than 60.   :p

**Comment by Windsander** [comment]
@Green-Sky 

-p " best quality, extremely detailed, keep main character, in outer space " --model ../../../sd-video/svd_xt.safetensors --vae ../../../sd-video/vae/diffusion_pytorch_model.fp16.safetensors --sampling-method lcm --strength 0.65 --style-ratio 10 --steps 60 --cfg-scale 1.0 --seed 15.0 -M img2vid -H 1024 -W 1024 --video-total-frames 14 --video-fps 8 --motion-bucket-id 42 -i ../../../io-test/input.png -o ../../../io-test/output.png -v

u can using this script, but it well cost a bunch of time... maybe wait for a day...  emmm   0_o   o_0

**Comment by Windsander** [comment]
image
 
 much faster than my PC... which looks like this:
 
image

more than 5000s .... 0x0

**Comment by Green-Sky** [comment]
Yea, it takes incredibility long...

Another way to speed things up would be using models that converge faster, did you test
https://huggingface.co/wangfuyun/AnimateLCM-SVD-xt ?

**Comment by Green-Sky** [comment]
wait... you are using 133GiB???, we need to optimize this. BTW, the f16 model file seems to just work. Also you can try `--type f16`, which will convert the model on-load in-memory.

**Comment by Windsander** [comment]
> wait... you are using 133GiB???, we need to optimize this. BTW, the f16 model file seems to just work. Also you can try `--type f16`, which will convert the model on-load in-memory.

ye... I'm trying to check in f32 models to get a better output XD.  
currently are not so large

image

**Comment by Windsander** [comment]
it not a good options to use prompt as ' in outer space'...
outer_space

cause it only darkness.. and some cosmic at edges

maybe its even not to use any text detail prompt, to specify scene.

I'm trying this script below:

```bash
# for Mac temp files cleaning
find . -name "._*" -type f -print
find . -name "._*" -type f -delete

# executing Stable Diffusion with params below
././cmake-build-release-gcc/bin/Release/sd\
 -p "\
 best quality, extremely detailed,\
 keep main character<lora:lcm-lora-sdv1-5:1>,\
 a puppy under an apple tree\
 "\
 --model ././sd-video/svd_xt.safetensors\
 --vae ././sd-video/vae/diffusion_pytorch_model.fp16.safetensors\
 --sampling-method lcm\
 --strength 0.65\
 --style-ratio 10\
 --steps 60\
 --cfg-scale 1.0\
 --seed 15.0\
 -M img2vid\
 -H 512 -W 512\
 --video-total-frames 14\
 --video-fps 8\
 --motion-bucket-id 42\
 -i ././io-test/input.png\
 -o ././io-test/output.png\
 -v
```

**Comment by Windsander** [comment]
now I'm trying this script below:

```bash
# for Mac temp files cleaning
find . -name "._*" -type f -print
find . -name "._*" -type f -delete

# executing Stable Diffusion with params below
././cmake-build-release-gcc/bin/Release/sd\
 -p "\
 best quality, extremely detailed,\
 keep main character<lora:lcm-lora-sdv1-5:1>,\
 a puppy under an apple tree\
 "\
 --model ././sd-video/svd_xt.safetensors\
 --vae ././sd-video/vae/diffusion_pytorch_model.fp16.safetensors\
 --sampling-method lcm\
 --strength 0.65\
 --style-ratio 10\
 --steps 60\
 --cfg-scale 1.0\
 --seed 15.0\
 -M img2vid\
 -H 512 -W 512\
 --video-total-frames 14\
 --video-fps 8\
 --motion-bucket-id 42\
 -i ././io-test/input.png\
 -o ././io-test/output.png\
 -v
```

with input pic below(not using empty start light in center pic anymore 🤡):
input

**Comment by Windsander** [comment]
also can add:

-n "\
 worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry,\
 Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy,\
 amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes,\
 deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms,\
 bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands,\
 connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands,\
 extra legs, bad legs, many legs, more than two legs, bad feet, extra feet\
 "\

**Comment by fszontagh** [comment]
I tried to build this pr on MS (with CUDA) to reproducate the img2vid params, but got this at the end:

> error: unknown argument: --video-total-frames

Maybe i using wrong sources?


But on first, on compile time i got this error:

> Z:\stable-diffusion.cpp\vae.hpp(555,14): error C2040: 'h': 'auto' differs in levels of indirection from 'ggml_tensor *' [Z:\stable-diffusion.cpp\build\stable-diffusion.vcxproj]

Which i think just a misspell. Need to modify vae.hpp at line 555 from

> auto h = decoder->forward(ctx, z);

to
> h = decoder->forward(ctx, z);

and line 547 from
> auto h = z;
to 
> ggml_tensor * h = z;

**Comment by x0rb0t** [comment]
@Windsander Hey, I took your branch with lifecycle implementation and made some fixes. I am working on web server api implementation you can check it here https://github.com/pintar-team/stable-diffusion.cpp/tree/master/examples/server

**Comment by Windsander** [comment]
> @Windsander Hey, I took your branch with lifecycle implementation and made some fixes. I am working on web server api implementation you can check it here https://github.com/pintar-team/stable-diffusion.cpp/tree/master/examples/server

emm. u can commit a merge request to this branch:
https://github.com/Windsander/stable-diffusion.cpp/tree/refact_process_flow

so, it well be easy to compare~ thx~~

**Comment by Windsander** [comment]
> > I tried to build this pr on MS (with CUDA) to reproducate the img2vid params, but got this at the end:
> > > error: unknown argument: --video-total-frames
> > 
> > 
> > Maybe i using wrong sources?
> 
> UPDATE: i just used wrong binary (Release / Debug). I got the same result as Green-Sky with cuda
> 
> But on first, on compile time i got this error:
> 
> > Z:\stable-diffusion.cpp\vae.hpp(555,14): error C2040: 'h': 'auto' differs in levels of indirection from 'ggml_tensor *' [Z:\stable-diffusion.cpp\build\stable-diffusion.vcxproj]
> 
> Which i think just a misspell. Need to modify vae.hpp at line 555 from
> 
> > auto h = decoder->forward(ctx, z);
> 
> to
> 
> > h = decoder->forward(ctx, z);
> 
> and line 547 from
> 
> > auto h = z;
> > to
> > ggml_tensor * h = z;

aw.... that my bad, for :
image

which is caused by this commit:
[fix: there is a necessary action to tell void* add sys-ref for not re…](https://github.com/leejet/stable-diffusion.cpp/pull/236/commits/e132df2b570c3209f852c9e07e875464512f2484) 
[e132df2](https://github.com/leejet/stable-diffusion.cpp/pull/236/commits/e132df2b570c3209f852c9e07e875464512f2484)
…lease data, cause z = ** in multi-thread ggml will make z unref and cause z->data = NULL. which will make vae input with NULL unet out put latent tensor data


but its necessary to use "auto h = z" at first, 
for upper reason :p

but sure, need to update a new one for that stupid duplicated 0x0..

**Comment by Windsander** [comment]
the original sad-xt is too slow, I'm currently try to use :
https://huggingface.co/wangfuyun/AnimateLCM-SVD-xt

which green-sky buddy suggest. and may need some update on code :p

**Comment by FSSRepo** [comment]
@Windsander Thank you very much for contributing to the project!, Perhaps in the future, we could improve code readability, as you may notice it's currently a jumble of things scattered everywhere. XD

**Comment by leejet** [comment]
@Windsander I've spent some time briefly reviewing your changes and have a few questions:

1. Why did you pass the prompt into Clip Vision, perform a simple embedding, and then conduct an ggml_out_prod operation with the hidden states encoded from the image? Is there any theoretical basis for this? I haven't seen such an operation in the original SVD repository (https://github.com/Stability-AI/generative-models/) or in ComfyUI.

2. Your pull request changes to input each frame separately into the UNet. However, this approach doesn't work because the temporal convolution in SVD UNet computes over adjacent frames, while the temporal attention computes attention between each frame. It's essential to input all frames together into the UNet, as this is the core of video generation; otherwise, it merely generates images independently and stitches them together.

I'm not sure how much you understand about SVD specifically. If you're not very familiar with the mechanism of SVD, I suggest you refrain from attempting to modify this part of the code. You can try reading the original repository or relevant ComfyUI code to understand the corresponding implementation.

When I implement some functionalities in sd.cpp, I usually do simple tests to compare the results with ComfyUI to verify if the implementation has any issues, such as the test function of the UNet model. If you plan to make changes, I suggest you perform similar validations. But as I mentioned, if you're not familiar with SVD, it's advisable not to attempt modifications; otherwise, you might encounter various unexpected problems and waste your time unnecessarily.

**Comment by leejet** [comment]
> I'm also going to add the functionality to save the generated videos directly in .mp4 format, solely using an open-source library for H.265 encoding with [libde265](https://github.com/strukturag/libde265).

@FSSRepo In my original plan, I intended to save the images generated by SVD in either webp or gif format, as this would make the introduction of third-party libraries more lightweight.

**Comment by Windsander** [comment]
> @Windsander I've spent some time briefly reviewing your changes and have a few questions:
> 
> 1. Why did you pass the prompt into Clip Vision, perform a simple embedding, and then conduct an ggml_out_prod operation with the hidden states encoded from the image? Is there any theoretical basis for this? I haven't seen such an operation in the original SVD repository (https://github.com/Stability-AI/generative-models/) or in ComfyUI.
> 2. Your pull request changes to input each frame separately into the UNet. However, this approach doesn't work because the temporal convolution in SVD UNet computes over adjacent frames, while the temporal attention computes attention between each frame. It's essential to input all frames together into the UNet, as this is the core of video generation; otherwise, it merely generates images independently and stitches them together.
> 
> I'm not sure how much you understand about SVD specifically. If you're not very familiar with the mechanism of SVD, I suggest you refrain from attempting to modify this part of the code. You can try reading the original repository or relevant ComfyUI code to understand the corresponding implementation.
> 
> When I implement some functionalities in sd.cpp, I usually do simple tests to compare the results with ComfyUI to verify if the implementation has any issues, such as the test function of the UNet model. If you plan to make changes, I suggest you perform similar validations. But as I mentioned, if you're not familiar with SVD, it's advisable not to attempt modifications; otherwise, you might encounter various unexpected problems and waste your time unnecessarily.

yep, I have found some part I've understand with wrong way, now I'm reconcerning SVD on more detail way, to found out what part caused output always as a mix of colors. 

 thx guys~ for every helps u provide~ XD

**Comment by Green-Sky** [comment]
found an interesting model:
https://civitai.com/models/372584/ipivs-morph-img2vid-animatediff-lcm-hyper-sd

> v3: [Hyper-SD](https://hyper-sd.github.io/) implementation - allows us to use AnimateDiff v3 Motion model with DPM and other samplers. Seems to result in improved quality, overall color and animation coherence.

**Comment by Windsander** [comment]
this merge be closed. after I finish my restudy, then will reopen again.

thx again for everyones help~. love & peace~  XD

**Pull request closed without merging**
