### PR TITLE
Remove default variables in c headers

### PR DESCRIPTION
**Pull request by stduhpf**
Fixes: https://github.com/leejet/stable-diffusion.cpp/issues/477

### CODE REVIEW

**Comment by stduhpf** [comment]
Hijacking this pr to also make the default slg scale to 0.

**Comment by SkutteOleg** [comment]
`std::vector` is not a thing in C as far as I'm aware 🤔

**Comment by stduhpf** [comment]
Damn you're right.

**Comment by stduhpf** [comment]
I'll change it to a C array later.

**Pull request merged**
