### PR TITLE
Feat: add Flux 1 Lite 8B (Freepik) support

### PR DESCRIPTION
**Pull request by stduhpf**
Diffusion model weights: https://huggingface.co/Freepik/flux.1-lite-8B-alpha/blob/main/flux.1-lite-8B-alpha.safetensors.

It's basically Flux 1 [Dev] with most double blocks removed. Flux 1 Lite Q4_k is smaller than Flux 1 Dev Q3_k, while delivering better image quality (in my subjective opinion). It's also about 25% faster during image generation.

` .\build\bin\Release\sd.exe --diffusion-model ..\ComfyUI\models\unet\flux.1-lite-8B-alpha-q4_k.gguf --vae ..\ComfyUI\models\vae\ae.q8_0.gguf --clip_l ..\ComfyUI\models\clip\clip_l.q8_0.gguf --t5xxl ..\ComfyUI\models\clip\t5xxl_q4_k.gguf -p "a lovely cat holding a sign says 'flux.cpp'" --cfg-scale 1.0 --sampling-method euler -t 24 --vae-tiling --color -v -W 1024 -H 1024`
output

| Flux 1 Dev Q3_k (5 114 284 416 Bytes) | Flux 1 Lite Q4_k (4 819 297 120 Bytes) |
| --- | --- |
| dev-q3_k | lite-q4_k |

### CODE REVIEW

**Comment by Green-Sky** [comment]
Tested this ontop of my [flash attention pr](https://github.com/leejet/stable-diffusion.cpp/pull/386), and the results are good :rocket: .

## cuda (rtx 2070 mobile / 8gb vram)
| quant | dims      | fa             | compute buffer size | speed    |
|-------|-----------|----------------|---------------------|----------|
| q3_k  | 512x512   | :red_circle:   | 398.50 MB(VRAM)     | 1.67s/it |
| q3_k  | 512x512   | :green_circle: | 248.50 MB(VRAM)     | 1.39s/it |
| q3_k  | 1024x512  | :red_circle:   | 942.75 MB(VRAM)     | 3.32s/it |
| q3_k  | 1024x512  | :green_circle: | 456.75 MB(VRAM)     | 2.62s/it |
| q3_k  | 768x768   | :red_circle:   | 1105.07 MB(VRAM)    | 3.91s/it |
| q3_k  | 768x768   | :green_circle: | 505.07 MB(VRAM)     | 3.01s/it |
| q3_k  | 1024x1024 | :red_circle:   | 2577.25 MB(VRAM)    | 8.06s/it |
| q3_k  | 1024x1024 | :green_circle: | 843.25 MB(VRAM)     | 5.79s/it |
| q4_k  | 512x512   | :red_circle:   | 398.50 MB(VRAM)     | 1.56s/it |
| q4_k  | 512x512   | :green_circle: | 248.50 MB(VRAM)     | 1.30s/it |
| q4_k  | 1024x512  | :red_circle:   | 942.75 MB(VRAM)     | 3.10s/it |
| q4_k  | 1024x512  | :green_circle: | 456.75 MB(VRAM)     | 2.43s/it |
| q4_k  | 768x768   | :red_circle:   | 1105.07 MB(VRAM)    | 3.64s/it |
| q4_k  | 768x768   | :green_circle: | 505.07 MB(VRAM)     | 2.79s/it |
| q4_k  | 1024x1024 | :red_circle:   | OOM |  |
| q4_k  | 1024x1024 | :green_circle: | 843.25 MB(VRAM) | 5.20s/it |

**Comment by Green-Sky** [comment]
With this model, the flash attention pr and vae-tiling, you can do some obscene stuff like q4_k 2048x1024 on my 8gig vram.
output

**Comment by stduhpf** [comment]
Flash Attention is still not supported on Vulkan sadly. I might try herging in https://github.com/ggerganov/llama.cpp/pull/10206 later to see how it goes.

**Comment by leejet** [comment]
Thank you for your contribution.

**Pull request merged**
