### PR TITLE
Add Euler, Heun and DPM++ (2M) samplers

### PR DESCRIPTION
**Pull request by ursg**
I don't like ancestral samplers, so I implemented the simplest deterministic ones: Euler and Heun sampling, based on their python equivalents from the k-diffusers package.

This also includes code to do the ```--sampling-method``` parameter parsing. And fixes the spelling of Euler. :)

### CODE REVIEW

**Comment by Green-Sky** [comment]
:rocket: 
I usually prefer the looks of Euler a over Euler. not sure if we should change the default.

**Comment by JohnClaw** [comment]
Add ddim sampler, please.

**Comment by ursg** [comment]
Also added DPM++ (2M) sampler, because I like that one, too!

**Comment by JohnClaw** [comment]
> Also added DPM++ (2M) sampler, because I like that one, too!

Would you be so kind to compile and upload a windows executable for your SD.cpp fork, please?

**Comment by Green-Sky** [comment]
> > Also added DPM++ (2M) sampler, because I like that one, too!
> 
> Would you be so kind to compile and upload an avx2 windows executable for your SD.cpp fork, please?

:laughing: someone cant wait for @leejet to merge this.

**Review by Green-Sky — CHANGES_REQUESTED** [review]
you are missing "sampling-method" and "sample-method"
eg. help tells you to use "sample-method" but its actually "sampling-method"

edit: you also changed "euler a" to "euler_a" as the parameter

**Comment by Happenedtostumblein** [comment]
Would inpainting a separate mode altogether, or is it a sampling type?

**Comment by Green-Sky** [comment]
did a test run of the samplers with default settings (20steps, 512x512) and the `artiusV21` model

## euler:
output_euler

## euler a:
output_euler_a

## heun:
output_heun

## dpm++ 2m:
output_dpm++2m

**Comment by Green-Sky** [comment]
> Would inpainting be a separate mode altogether, or is it a sampling type?
> 
> Edit: I guess inpainting is just part of img2img but does anyone know how to apply mask technique vs sketch?

It is very much a different mode, yes, iirc img2img with masking or something like that.
Sketch was something else entirely iirc, i think that was with a ControlNet.

**Comment by ursg** [comment]
Added another one: The modified version of DPM++ (2M) from [this thread](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8457) over in AUTOMATIC1111's webui discussions. Apparently, there are mathematical arguments why the unmodified method could sometimes overstep and produce exaggerated edge artefacts, and this change fixes that.

**Comment by ursg** [comment]
> you are missing "sampling-method" and "sample-method" eg. help tells you to use "sample-method" but its actually "sampling-method"

That one is fixed now, thanks!

**Comment by ursg** [comment]
> you also changed "euler a" to "euler_a" as the parameter

True, I considered it more practical not to have spaces inside command line arguments like that. Not good?

**Comment by Green-Sky** [comment]
## dpm++ 2 v2
output_dpm++2mv2

**Comment by leejet** [comment]
Great! Thank you for your contribution. However, I prefer to use euler a as the default sampling method, as stable-diffusion-weiui does. So I made some small changes.

**Pull request merged**
